spring:
  application:
    name: store
  output:
    ansi:
      enabled: ALWAYS
  jwt:
    secret: ${JWT_SECRET}
    accesstokenexpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}